#config_paper.yaml

# 모델 관련 설정
model_args:
  use_cuda: True
  encoder_size: 64
  decoder_size: 128
  in_length: 16
  out_length: 25
  grid_size: [13, 3]
  soc_conv_depth: 64
  conv_3x1_depth: 16
  dyn_embedding_size: 32
  input_embedding_size: 32
  num_lat_classes: 3
  num_lon_classes: 2
  use_maneuvers: True

dataset_args:
  nbr_mode: 2
  t_h: 15
  t_f: 25
  d_s: 1

# 학습 루프 관련 설정
train_args:
  pretrain_epochs: 50
  train_epochs: 450
  batch_size: 512

# 데이터 경로
data_paths:
  train_set: 'highD/processed/split_712/TrainSet.h5'
  val_set: 'highD/processed/split_712/ValSet.h5'
  test_set: 'highD/processed/split_712/TestSet.h5'
  save_dir: 'ckpts/exp2'